[package]
name = "hi_mom_website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.10"
actix-rt = "2.5.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"

